name: Docker Image CI
on:
  push:
    branches: [ release ]
  workflow_dispatch:
jobs:
  test:
    name: "Test"
    uses: "./.github/workflows/integration-tests.yml"
  build:
    name: "Build & Publish"
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set Version
      run: |
        CI_VERSION=$(cat ./src/VERSION)
        echo "CI_VERSION=$CI_VERSION" >> $GITHUB_ENV
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shrihariprakash/liquid:$CI_VERSION -t "shrihariprakash/liquid:latest"
    - name: Docker Push
      run: docker push shrihariprakash/liquid --all-tags
